docs(server/storage): more specific PlayerEntity contract
Qbox-project/qb-core pull request #42
Opened 2023-02-15 16:40 UTC by Manason

## Description
- initial pass to define what a PlayerEntity is. Based off code analysis. Still some fields which I wasn't able to figure out the type for.

## Checklist

- [ ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My code fits the style guidelines.
- [x] My PR fits the contribution guidelines.

2023-02-15 16:49 UTC, BerkieBb requested changes

2023-02-15 16:49 UTC, BerkieBb commented on server/storage.lua
> +---@field money {cash: number, bank: number, crypto: number}
This should be in sync with the confit instead of hardcoded

2023-02-15 18:35 UTC, Rav3n95 approved these changes

2023-02-16 11:25 UTC, FjamZoo approved these changes

2023-02-17 08:34 UTC, BerkieBb approved these changes

2023-02-17 16:18 UTC, merged